//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverInsuranceHistory
    {
        public int HistoryID { get; set; }
        public int DriverID { get; set; }
        public int PolicyID { get; set; }
        public int Year { get; set; }
        public bool HadAccident { get; set; }
        public decimal KBM { get; set; }
        public System.DateTime LastUpdated { get; set; }
    
        public virtual Drivers Drivers { get; set; }
        public virtual Policies Policies { get; set; }
    }
}
