//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class LifeAndHealth
    {
        public int LifeAndHealthID { get; set; }
        public int PolicyID { get; set; }
        public int Age { get; set; }
        public string Gender { get; set; }
        public int HealthConditionID { get; set; }
        public string Occupation { get; set; }
    
        public virtual HealthConditions HealthConditions { get; set; }
        public virtual Policies Policies { get; set; }
    }
}
