//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logs
    {
        public int LogID { get; set; }
        public string TableName { get; set; }
        public string Action { get; set; }
        public string ChangedData { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public string UserName { get; set; }
        public Nullable<int> EmployeeID { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
