//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Properties
    {
        public int PropertyID { get; set; }
        public int PolicyID { get; set; }
        public int PropertyTypeID { get; set; }
        public string Address { get; set; }
        public decimal Area { get; set; }
        public decimal Value { get; set; }
    
        public virtual Policies Policies { get; set; }
        public virtual PropertyTypes PropertyTypes { get; set; }
    }
}
