//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicles
    {
        public int VehicleID { get; set; }
        public int PolicyID { get; set; }
        public int ModelID { get; set; }
        public string VIN { get; set; }
        public int Year { get; set; }
        public string LicensePlate { get; set; }
    
        public virtual Policies Policies { get; set; }
        public virtual VehicleModels VehicleModels { get; set; }
    }
}
